me = 'https://tetr.io/api/users/me'
ribbon = 'https://tetr.io/api/server/ribbon'
room = 'https://tetr.io/#'
rooms = 'https://tetr.io/api/rooms'
dms = 'https://tetr.io/api/dms/'
friend = 'https://tetr.io/api/relationships/friend'
unfriend = 'https://tetr.io/api/relationships/remove'
