me = 'https://tetr.io/api/users/me'
ribbon = 'https://tetr.io/api/server/ribbon'
tetrioJs = 'https://tetr.io/tetrio.js'
room = 'https://tetr.io/#'
rooms = 'https://tetr.io/api/rooms'
enviorment = 'https://tetr.io/api/server/environment'
dms = 'https://tetr.io/api/dms/'
